export const AUTH_ADMIN = 'AUTH_ADMIN';
export const AUTH_ERROR = 'AUTH_ERROR';

export const CREATE_THEME = 'CREATE_THEME';
export const FETCH_THEMES = 'FETCH_THEMES';
export const FETCH_THEME = 'FETCH_THEME';
export const EDIT_THEME = 'EDIT_THEME';
export const DELETE_THEME = 'DELETE_THEME';

export const CREATE_TOPIC = 'CREATE_TOPIC';
export const FETCH_TOPICS = 'FETCH_TOPICS';
export const FETCH_TOPIC = 'FETCH_TOPIC';
export const EDIT_TOPIC = 'EDIT_TOPIC';
export const DELETE_TOPIC = 'DELETE_TOPIC';

export const CREATE_TEAMACCESS = 'CREATE_TEAMACCESS';
export const FETCH_TEAMACCESSS = 'FETCH_TEAMACCESSS';
export const FETCH_TEAMACCESS = 'FETCH_TEAMACCESS';
export const EDIT_TEAMACCESS = 'EDIT_TEAMACCESS';
export const DELETE_TEAMACCESS = 'DELETE_TEAMACCESS';

export const CREATE_EPISODE = 'CREATE_EPISODE';
export const FETCH_EPISODES = 'FETCH_EPISODES';
export const FETCH_EPISODE = 'FETCH_EPISODE';
export const EDIT_EPISODE = 'EDIT_EPISODE';
export const DELETE_EPISODE = 'DELETE_EPISODE';

export const CREATE_STORY = 'CREATE_STORY';
export const FETCH_STORYS = 'FETCH_STORYS';
export const FETCH_STORY = 'FETCH_STORY';
export const EDIT_STORY = 'EDIT_STORY';
export const DELETE_STORY = 'DELETE_STORY';

export const CREATE_SESSIONBETA = 'CREATE_SESSIONBETA';
export const FETCH_SESSIONBETAS = 'FETCH_SESSIONBETAS';
export const FETCH_SESSIONBETA = 'FETCH_SESSIONBETA';
export const EDIT_SESSIONBETA = 'EDIT_SESSIONBETA';
export const DELETE_SESSIONBETA = 'DELETE_SESSIONBETA';

export const CREATE_JOURNALQUESTION = 'CREATE_JOURNALQUESTION';
export const FETCH_JOURNALQUESTIONS = 'FETCH_JOURNALQUESTIONS';
export const FETCH_JOURNALQUESTION = 'FETCH_JOURNALQUESTION';
export const EDIT_JOURNALQUESTION = 'EDIT_JOURNALQUESTION';
export const DELETE_JOURNALQUESTION = 'DELETE_JOURNALQUESTION';